name: ChatLog
version: 1.1.0
description: Chatlog Plugin

author: Skillkiller
website: https://skillkiller.de
depend: []

main: de.skillkiller.chatlog.main.Core

commands:
  chatlog:
    description: Erstelle einen Chatlog
    aliases: [log, chat, l]
    usage: /chatlog
  timeset:
    description: Stellt den Zeitbereicht fur den Timecode ein
    usage: /timeset [Time before in Seconds] [Time after in Seconds]
    permission: chatlog.time
    permission-message: Deine Rechte reichen nicht aus